# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: global-score-indexer
contracts:
- name: AgentRegistry
  handler: src/EventHandlers.ts
  events:
  - event: Registered(uint256 indexed agentId, string agentURI, address indexed owner)
networks:
- id: 1
  start_block: 21805560
  contracts:
  - name: AgentRegistry
    address:
    - 0x8004A169FB4a3325136EB29fA0ceB6D2e539a432
- id: 56
  start_block: 46850000
  contracts:
  - name: AgentRegistry
    address:
    - 0x8004A169FB4a3325136EB29fA0ceB6D2e539a432
- id: 137
  start_block: 68450000
  contracts:
  - name: AgentRegistry
    address:
    - 0x8004A169FB4a3325136EB29fA0ceB6D2e539a432
- id: 8453
  start_block: 41453265
  contracts:
  - name: AgentRegistry
    address:
    - 0x8004A169FB4a3325136EB29fA0ceB6D2e539a432
unordered_multichain_mode: true
preload_handlers: true
